# Generated by Django 2.0.2 on 2018-03-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgabe', models.PositiveSmallIntegerField()),
                ('max_punkte', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='AufgabenAbgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgabe', models.PositiveSmallIntegerField()),
                ('punkte', models.DecimalField(decimal_places=1, max_digits=4)),
                ('abgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='notenrechner.Abgabe')),
            ],
        ),
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('jahrgang', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Klausur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('nummer', models.PositiveSmallIntegerField()),
                ('anzahl_aufgaben', models.IntegerField(default=3)),
                ('fach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notenrechner.Fach')),
                ('klasse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klausuren', to='notenrechner.Klasse')),
            ],
        ),
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=60)),
                ('nachname', models.CharField(max_length=60)),
                ('klasse', models.ManyToManyField(related_name='schueler', to='notenrechner.Klasse')),
            ],
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='klausur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='notenrechner.Klausur'),
        ),
        migrations.AddField(
            model_name='abgabe',
            name='klausur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abgaben', to='notenrechner.Klausur'),
        ),
        migrations.AddField(
            model_name='abgabe',
            name='schueler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abgaben', to='notenrechner.Schueler'),
        ),
    ]
