# Generated by Django 2.0.2 on 2018-03-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notenrechner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schueler',
            old_name='klasse',
            new_name='klassen',
        ),
    ]
