# Generated by Django 2.0.2 on 2018-03-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notenrechner', '0003_remove_klausur_anzahl_aufgaben'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abgabe',
            unique_together={('klausur', 'schueler')},
        ),
        migrations.AlterUniqueTogether(
            name='aufgabe',
            unique_together={('klausur', 'aufgabe')},
        ),
        migrations.AlterUniqueTogether(
            name='aufgabenabgabe',
            unique_together={('abgabe', 'aufgabe')},
        ),
        migrations.AlterUniqueTogether(
            name='klasse',
            unique_together={('name', 'jahrgang')},
        ),
        migrations.AlterUniqueTogether(
            name='klausur',
            unique_together={('klasse', 'fach', 'nummer')},
        ),
        migrations.AlterUniqueTogether(
            name='schueler',
            unique_together={('vorname', 'nachname')},
        ),
    ]
