# Generated by Django 2.0.2 on 2018-03-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notenrechner', '0004_auto_20180304_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='klausur',
            name='anzahl_aufgaben',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterUniqueTogether(
            name='klausur',
            unique_together={('fach', 'klasse', 'nummer')},
        ),
    ]
