# Generated by Django 2.0.2 on 2018-03-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notenrechner', '0005_auto_20180304_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aufgabe',
            old_name='aufgabe',
            new_name='nummer',
        ),
        migrations.AlterField(
            model_name='klausur',
            name='anzahl_aufgaben',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Aufgaben'),
        ),
        migrations.AlterUniqueTogether(
            name='aufgabe',
            unique_together={('klausur', 'nummer')},
        ),
    ]
