# Generated by Django 2.0.2 on 2018-03-05 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notenrechner', '0006_auto_20180304_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schueler',
            options={'ordering': ('nachname',)},
        ),
        migrations.AlterField(
            model_name='aufgabenabgabe',
            name='aufgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notenrechner.Aufgabe'),
        ),
    ]
