# Generated by Django 2.0.2 on 2018-03-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notenrechner', '0009_auto_20180317_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='schueler',
            name='zusatz',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='schueler',
            unique_together={('vorname', 'nachname', 'zusatz')},
        ),
    ]
